### ISSUE TITLE
MusicXML export: Nested tuplets

### ISSUE THREAD

**Issue by uliska** [wbsoft/python-ly#25] opened 2015-05-26 08:00 UTC
Minimal working example after description in #24:

```
{
  \tuplet 3/2 {
    c'2 d' 
      \tuplet 5/4 {
        e'8 f' e' d' c'
      }
  }
}
```

When exporting this to MusicXML the inner tuplets are not nested but "merged".  Re-importing leads to the following LilyPond code:

```
c2*2/3 d \times 8/15 {
    e8 f e d c
  }
```
So the "outer" tuplets are hidden and only realized through the `time-modification` element, while the 3/2 and 5/4 are simply multiplied for the inner tuplets

**Comment by PeterBjuhr** [comment] 2015-05-26 08:41
First of all it should be said that musicxml2ly doesn't handle nested tuplets (well), so re-importing can't be a good judge of the state of the export functionality.

That said there still is an issue with nested tuplets. In fact the problem is more general and concerns all tuplets nested or plain where the `time-modification` element can't give all the information about the tuplet.

**Comment by uliska** [comment] 2015-05-26 09:01
> First of all it should be said that musicxml2ly doesn't handle nested 
> tuplets (well), so re-importing can't be a good judge of the state of 
> the export functionality.
>

OK, but in this case the reimported ly seems to match the exported MusicXML

> That said there still is an issue with nested tuplets. In fact the 
> problem is more general and concerns all tuplets nested or plain where 
> the |time-modification| element can't give all the information about 
> the tuplet.
>
>
OK, can't judge on that.

**Comment by PeterBjuhr** [comment] 2015-05-29 19:49
Your example actually doesn't have the issue I mentioned.

This is what an import in Finale (2011) looks like:

![image](https://cloud.githubusercontent.com/assets/355116/7891314/ffd2e2e4-064b-11e5-9d5c-27c353ebc90a.png)

Looks pretty good. But I found one error in the xml file - the first tuplet (outer) doesn't get stopped.

**Comment by PeterBjuhr** [comment] 2015-05-29 20:08
The following example could exemplify the remaining issue I mentioned:

````lilypond
{
  \tuplet 3/2 {
    \tuplet 3/2 {
      c'8 d' e'
    }
    d'4 e'
  }
  d'2
}
````

![image](https://cloud.githubusercontent.com/assets/355116/7891605/4c78230a-064e-11e5-89e0-cbaff77fd348.png)

Because both tuplets start with the same eight note the outer tuplet isn't correctly interpreted as 3 instead of 2 *quarters* and the tuplet wrongly doesn't include the last `e'`.

**Comment by PeterBjuhr** [comment] 2015-05-29 20:47
> I found one error in the xml file - the first tuplet (outer) doesn't get stopped.

Fixed in 0e51cb64757f286d8fe4729d69f1ab560880f275.

**Closed** 2015-05-30 09:53 UTC
Labels: musicxml export

**Comment by PeterBjuhr** [comment] 2015-05-30 09:57
Image from Finale to confirm the latest fix:

![image](https://cloud.githubusercontent.com/assets/355116/7896707/f0079de2-06c2-11e5-8809-529be97ebc10.png)

**Comment by uliska** [comment] 2015-06-01 08:35
Exporting and reimporting my initial example gives this in LilyPond:

![nested-tuplets-3](https://cloud.githubusercontent.com/assets/1812148/7909001/853257ea-0849-11e5-9273-da66e5e87d5b.png)

But from your Finale import I assume the MusicXML is correct (I can understand what is encoded there, although I have to admit I feel it's strange (conceptually from the MusicXML side)). So this is obviously an issue with `musicxml2ly`.

The second example renders like this when reimported.

![nested-tuplets-alternative-1](https://cloud.githubusercontent.com/assets/1812148/7909060/ddf9d40c-0849-11e5-9aa4-63017f0b728c.png)

So obviously `musicxml2ly` doesn't properly handle nested tuplets.

**Comment by PeterBjuhr** [comment] 2015-06-01 08:49
Basically MusicXML handles nested elements by numbering them. 

In the case of tuplets I can agree that this leads to strange things conceptually. The second tuplet should only be allowed inside the first tuplet. But with this system it's possible to end the first tuplet after the second is started but before it's ended.

**Comment by uliska** [comment] 2015-06-01 08:58
I would find it much better to have tuplets behave like actual *elements* that *contain* their music. What I find awkward about the MusicXML approach is that the resulting tuplet notes are not really treated as nested. Instead they are treated like the "actual" notes.

If you export the following:

```lilypond
{
  \tuplet 3/2 {
    \tuplet 3/2 {
      c'8 d' e'
    }
    d'4 e'
  }
  d'2
}
```

The last notes are encoded as `8/27` notes, and the overall `<divisions>` are 54 (in the original Ferneyhough example they were some 10.000s). This looks very much like an approach that is targeted at *playback* rather than semantic encoding. It's just discussed how long the note is *to be played* and not what it *means*.

When actually getting in touch with it I more and more realize how limited MusicXML actually is, and I'm more or less sure that it can't be used as a proper way to do long-term archiving of publishers' catalogues or to do serious scholarly work.

**Comment by PeterBjuhr** [comment] 2015-06-01 09:19
You're right about the the `<divisions>` element (and the `<duration>` element for the individual notes). They are meant to hold information for midi and not for the notation. But they are nevertheless often interpreted by the importers in a way that effects also the semantic meaning.

--

I don't know if it's fair to request of MusicXML to be a format for long-term archiving. To me it's an exchange format for quick exchanges between whatever format is actually intended for use. 

Previously you would have a hard time exchanging the simplest score between Finale and Sibelius with the exception of using midi or reentering the whole thing. But now MusicXML have solved that problem quite well.

**Comment by uliska** [comment] 2015-06-01 09:27
Yes, that's the purpose of MusicXML. But the danger is that people (especially in the publishing domain) consider it as the solution to their problems with long-term data management. And as an excuse to stick to outdated tools like Finale and Sibelius ...

By now I'm sure that MEI is by far better suited for both academic and for data-management purposes. But as Perry Roland put it: What immediately comes to mind when you're thinking about that dark brown soft drink is never "Sinalco", it's always "Coke". And it's similar with MusicXML.

**Comment by uliska** [comment] 2015-06-01 09:29
To be more concrete: Editors I have recently discussed with told me: We use Finale because it's so convenient to achieve our desired visual appearance with. For the Open Access and data mining geeks we'll simply export to MusicXML and they can do with it what they want.
But I saw someone trying to make sense of that MusicXML data, and "they" won't be able to do anything useful with that data.

**Comment by uliska** [comment] 2015-06-02 14:57
> I don't know if it's fair to request of MusicXML to be a format for long-term archiving. 

Well:
"MusicXML was designed from the ground up for sharing sheet music files between applications, and for archiving sheet music files for use in the future. " *(First sentence on musicxml.com)*

**Comment by PeterBjuhr** [comment] 2015-06-02 15:35
You have a point. Nevertheless, the syntax of MusicXML seems to me pretty stable so in that respect it may be suitable for archiving. It all depends on what you are comparing with I guess; if you compare with midi then MusicXML carries a wealth of musical information.

**Comment by MilesMorel** [comment] 2020-07-06 19:38
I'd agree that the design of MusicXML leaves much to be desired but we're stuck with it for now. Using forward and backup to change voices is a pretty odd design choice considering that the time arrow of music is always forwards. I much would have preferred invisible rests so that each voice fills a measure - this is much more friendly for working with arrays. Similarly, the tuplet design is pretty rough. It was designed in the late 90s so maybe decisions were made to shave off file size. Either way, a more modern, JS-friendly MusicXML format certainly would have accelerated the progress of sheet music on the web. Unfortunately, without support from Sib/Finale/Musescore/GuitarPro etc. there isn't much hope.
